# -*- coding: utf-8 -*-
"""24_09_02_hello_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ymk6343/2024-09-cpf-mon/blob/main/24_09_02_hello_world.ipynb
"""

print("hello World")

